name = "pongo"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[build]
command = "wasm-pack build --target web --out-dir worker/pkg lobby_worker && cp lobby_worker/index.html worker/pkg/index.html"

[assets]
directory = "./worker/pkg"
binding = "ASSETS"
html_handling = "auto-trailing-slash"

[durable_objects]
bindings = [{ name = "MATCH", class_name = "MatchDO" }]

[[migrations]]
tag = "v1"
new_classes = ["MatchDO"]
